#Configurations for Image Collector

arch_name: 'resnet50'
best_state_path: '/export/sc-crisis-02/experiments/belmont_system/images/relevancy/model/best_state.pth'

thread_size: 5

redis:
  host: 10.4.2.95
  port: 6379 
  input_q: 200204095933_emsc_landslide_image_IMG_RELEVANCY_INQ

es:
  host: 10.4.2.107
  port: 9500
  name: 200204095933_emsc_landslide_image_img_index
