#Configurations for Image Collector
downloader_thread_size: 10

path_to_download_imgs: /Users/umair/Desktop/QCRI/belmont_system/images/image_collector/downloaded_images

redis:
  host: 10.4.2.95
  port: 6379 
  input_q: 200204095933_emsc_landslide_image_IMG_DOWNLOAD_INQ
  output_qs:
    - _IMG_INCIDENT_MODEL_INQ
    - _IMG_RELEVANCY_INQ
    - _IMG_DEDUP_INQ
    - _IMG_TWEET_INFO

# #tweet info should be other module responsibility
# tweet_info_q: 200204095933_emsc_landslide_image_tweets_info

cache:
  host: 10.4.2.107
  port: 9500 
  name: _img_url_cache
