#Configurations for Image Collector
thread_size: 1

redis:
  host: 10.4.2.95
  port: 6379 
  input_q: 200204095933_emsc_landslide_image_IMG_INCIDENT_MODEL_INQ


es:
  host: 10.4.2.107
  port: 9500
  name: 200204095933_emsc_landslide_image_img_index
